# frontend/Dockerfile

FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

# Copy frontend code
COPY . /app/frontend

# Install Python deps
RUN pip install --no-cache-dir \
    "numpy<2" \
    streamlit \
    requests \
    pandas

# Expose Streamlit port
EXPOSE 8501

# BACKEND_URL will be injected by docker-compose or Cloud Run
ENV BACKEND_URL=http://backend:8000

# Run Streamlit app
CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
